### ISSUE TITLE
Module crashes on init

### ISSUE THREAD

**Issue by luizfeldmann** [lwfinger/rtl8190p#7]
Hi
I just installed and tested your module on Lubuntu 20.04 with kernel 5.4.
Below is the output from dmesg.
I'm available work together to debug your module if you agree.

[   25.466902] 8190p: loading out-of-tree module taints kernel.
[   25.467142] 8190p: module verification failed: signature and/or required key missing - tainting kernel
[   25.467764] rtllib_crypt: registered algorithm 'NULL'
[   25.467765] rtllib_crypt: registered algorithm 'TKIP'
[   25.467766] rtllib_crypt: registered algorithm 'CCMP'
[   25.467767] rtllib_crypt: registered algorithm 'WEP'
[   25.467767] 
               Linux kernel driver for RTL8192 based WLAN cards
[   25.467768] Copyright (c) 2007-2008, Realsil Wlan
[   25.470982] BUG: unable to handle page fault for address: ffffffffc0a5b900
[   25.470986] #PF: supervisor write access in kernel mode
[   25.470987] #PF: error_code(0x0003) - permissions violation
[   25.470988] PGD 4000e067 P4D 4000e067 PUD 40010067 PMD 70f3c067 PTE 718e4061
[   25.470993] Oops: 0003 [#1] SMP PTI
[   25.470996] CPU: 1 PID: 454 Comm: systemd-udevd Tainted: G           OE     5.4.0-40-generic #44-Ubuntu
[   25.470998] Hardware name: System manufacturer System Product Name/P5KPL-AM-CKD-VISUM-SI, BIOS 0312    01/21/2009
[   25.471010] RIP: 0010:TSInitialize+0x2e5/0x370 [8190p]
[   25.471013] Code: 00 66 41 89 94 24 5a 01 00 00 e8 f6 5a 01 00 49 8b 97 20 21 00 00 48 8b 45 c8 4d 89 a7 20 21 00 00 49 89 04 24 49 89 54 24 08 <4c> 89 22 49 81 c4 d0 01 00 00 4c 39 65 d0 0f 85 1b ff ff ff 48 8b
[   25.471014] RSP: 0018:ffffb4c70043f998 EFLAGS: 00010246
[   25.471016] RAX: ffff8e446da829d8 RBX: ffff8e446da829f0 RCX: 0000000000000000
[   25.471017] RDX: ffffffffc0a5b900 RSI: ffff8e446da82a90 RDI: ffff8e446da82b80
[   25.471019] RBP: ffffb4c70043f9e8 R08: 0000000000000000 R09: ffff8e447cc02fc0
[   25.471020] R10: 0000000000000dc0 R11: 0000000000000000 R12: ffff8e446da829e8
[   25.471022] R13: 0000000000000001 R14: ffff8e446da82b80 R15: ffff8e446da808c0
[   25.471024] FS:  00007fdbccb84880(0000) GS:ffff8e447d280000(0000) knlGS:0000000000000000
[   25.471025] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[   25.471027] CR2: ffffffffc0a5b900 CR3: 000000007580e000 CR4: 00000000000406e0
[   25.471028] Call Trace:
[   25.471039]  alloc_rtllib_rsl+0x23b/0x2f0 [8190p]
[   25.471048]  rtl8192_pci_probe+0x7c/0x2f0 [8190p]
[   25.471053]  local_pci_probe+0x48/0x80
[   25.471055]  pci_device_probe+0x10f/0x1b0
[   25.471059]  really_probe+0x159/0x3e0
[   25.471061]  driver_probe_device+0xbc/0x100
[   25.471063]  device_driver_attach+0x5d/0x70
[   25.471064]  __driver_attach+0x8f/0x150
[   25.471066]  ? device_driver_attach+0x70/0x70
[   25.471069]  bus_for_each_dev+0x7e/0xc0
[   25.471071]  driver_attach+0x1e/0x20
[   25.471073]  bus_add_driver+0x152/0x1f0
[   25.471075]  driver_register+0x74/0xd0
[   25.471077]  __pci_register_driver+0x57/0x60
[   25.471084]  rtl8192_pci_module_init+0x104/0x118 [8190p]
[   25.471091]  ? rtllib_crypto_tkip_init+0x17/0x17 [8190p]
[   25.471094]  do_one_initcall+0x4a/0x1fa
[   25.471097]  ? kfree+0x231/0x250
[   25.471100]  ? _cond_resched+0x19/0x30
[   25.471101]  ? kmem_cache_alloc_trace+0x16c/0x240
[   25.471105]  do_init_module+0x62/0x250
[   25.471107]  load_module+0x10b8/0x1200
[   25.471111]  __do_sys_finit_module+0xbe/0x120
[   25.471112]  ? __do_sys_finit_module+0xbe/0x120
[   25.471115]  __x64_sys_finit_module+0x1a/0x20
[   25.471117]  do_syscall_64+0x57/0x190
[   25.471120]  entry_SYSCALL_64_after_hwframe+0x44/0xa9
[   25.471122] RIP: 0033:0x7fdbcd10470d
[   25.471124] Code: 00 c3 66 2e 0f 1f 84 00 00 00 00 00 90 f3 0f 1e fa 48 89 f8 48 89 f7 48 89 d6 48 89 ca 4d 89 c2 4d 89 c8 4c 8b 4c 24 08 0f 05 <48> 3d 01 f0 ff ff 73 01 c3 48 8b 0d 53 f7 0c 00 f7 d8 64 89 01 48
[   25.471126] RSP: 002b:00007ffd628eb7d8 EFLAGS: 00000246 ORIG_RAX: 0000000000000139
[   25.471128] RAX: ffffffffffffffda RBX: 0000555d3fd366d0 RCX: 00007fdbcd10470d
[   25.471129] RDX: 0000000000000000 RSI: 00007fdbccfe1ded RDI: 0000000000000006
[   25.471130] RBP: 0000000000020000 R08: 0000000000000000 R09: 0000000000000000
[   25.471132] R10: 0000000000000006 R11: 0000000000000246 R12: 00007fdbccfe1ded
[   25.471133] R13: 0000000000000000 R14: 0000555d3fd41780 R15: 0000555d3fd366d0
[   25.471135] Modules linked in: 8190p(OE+) serio_raw snd_seq_device snd_timer snd soundcore asus_atk0110 mac_hid sch_fq_codel parport_pc ppdev lp parport ip_tables x_tables autofs4 btrfs xor zstd_compress raid6_pq libcrc32c dm_mirror dm_region_hash dm_log i915 video i2c_algo_bit drm_kms_helper syscopyarea sysfillrect sysimgblt fb_sys_fops psmouse i2c_i801 pata_acpi drm lpc_ich r8169 realtek floppy
[   25.471154] CR2: ffffffffc0a5b900
[   25.471156] ---[ end trace 84f3da099ccb07a1 ]---
[   25.471165] RIP: 0010:TSInitialize+0x2e5/0x370 [8190p]
[   25.471166] Code: 00 66 41 89 94 24 5a 01 00 00 e8 f6 5a 01 00 49 8b 97 20 21 00 00 48 8b 45 c8 4d 89 a7 20 21 00 00 49 89 04 24 49 89 54 24 08 <4c> 89 22 49 81 c4 d0 01 00 00 4c 39 65 d0 0f 85 1b ff ff ff 48 8b
[   25.471168] RSP: 0018:ffffb4c70043f998 EFLAGS: 00010246
[   25.471170] RAX: ffff8e446da829d8 RBX: ffff8e446da829f0 RCX: 0000000000000000
[   25.471171] RDX: ffffffffc0a5b900 RSI: ffff8e446da82a90 RDI: ffff8e446da82b80
[   25.471172] RBP: ffffb4c70043f9e8 R08: 0000000000000000 R09: ffff8e447cc02fc0
[   25.471174] R10: 0000000000000dc0 R11: 0000000000000000 R12: ffff8e446da829e8
[   25.471175] R13: 0000000000000001 R14: ffff8e446da82b80 R15: ffff8e446da808c0
[   25.471177] FS:  00007fdbccb84880(0000) GS:ffff8e447d280000(0000) knlGS:0000000000000000
[   25.471179] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[   25.471180] CR2: ffffffffc0a5b900 CR3: 000000007580e000 CR4: 00000000000406e0

**Comment by lwfinger** [comment]
It is not my module. It comes from Realtek, and I make it available. The only thing I guarantee is that it will build. I do not have the device, thus I cannot test.
